### ISSUE TITLE
make use of the age function in webtrees

### ISSUE THREAD

**Issue by HerzScheisse** [Tywed/telegram#2]
hi... 

maybe use the [age function of webtrees](https://github.com/fisharebest/webtrees/blob/main/app/Age.php) to wirte the year in `1 year / 5 years` (number + word)

![telegram module age](https://github.com/user-attachments/assets/800727c9-8abd-4818-b67a-4cdece449faf)

**Comment by Tywed** [comment]
Yes, thank you for pointing out that possibility. I will try to implement it in future releases.
